---
title: "Pet adoption"
author: "Group 2"
date: "r Sys.Date()"
output: pdf_document
  pdf_document:
    highlight: tango
    toc: false
    df_print: kable
    fig_caption: no
    number_sections: no
    dev: pdf
  html_document:
    highlight: tango
    self_contained: true
    theme: paper
    toc: no
    df_print: kable
    fig_caption: no
    number_sections: no
    smart: yes
    dev: svg
geometry: margin=1in
fontsize: 11pt
documentclass: article
---

```{r setup, include = FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(echo = TRUE)

# Load required packages
suppressPackageStartupMessages(library(tidyverse, quietly = TRUE))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))

```

##Introduction

###

##<EDA>
```{r}
pet_data <- read.csv(pet_adoption_data)
```

```{r}
pet_adoption_data <- pet_data
```

* It was hard to load data in first chunk, therefore I found to load data and changed its name.

```{r}
ggplot(pet_adoption_data) +
  geom_bar(mapping = aes(x = PetType, fill = PetType), stat = "count", color = "black") +
  labs(title = "Ratio of Pet Type", x = "Pet Type", y = "Count")
```
* First, I analyzed the dataset which PerType are proportioned. This graph shows that the Dog has the most while Bird has the least.

```{r}
pet_adoption_data$AgeMonths <- ifelse(is.na(pet_adoption_data$AgeMonths), 0, pet_adoption_data$AgeMonths)

pet_adoption_data$AgeGroup = cut(pet_adoption_data$AgeMonths,
                                 breaks = c(0, 30, 60, 90, 120, 150, 180, Inf),                                 labels = c("0-30 months", "31-60 months", "61-90 months", "91-120 months", "121-150 months", "151-180 months", "181+ months"), right = FALSE)
```